# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/reg
Content-Type: application/json

{
  "email" : "sid1ikdfov.d111s@gmail.com",
  "password": "qwerty007",
  "role" : "TEACHER"
}



###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email" : "sidikdfov.d111s@gmail.com",
  "password": "qwerty007"
}

###

GET http://localhost:8080/logout
AUTH: 2f1b4371-b499-4c8d-8305-6a691c29937d

###

GET http://localhost:8080/main
AUTH: 02a6c8fe-adf3-4b50-9ba8-654561908fc8

###


