-- auto-generated definition
create table ivavprp.achievement
(
    id bigint generated by default as identity
        constraint achievement_pkey
            primary key,
    name varchar(255),
    path varchar(255),
    points integer not null
);
​
alter table ivavprp.achievement owner to postgres;
​
create unique index achievements_id_uindex
    on ivavprp.achievement (id);
​
-- auto-generated definition
create table ivavprp.skill
(
    id bigint generated by default as identity
        constraint skill_pkey
            primary key,
    name varchar(255),
    points integer not null
);
​
alter table ivavprp.skill owner to postgres;
​
-- auto-generated definition
create table ivavprp.skills_achievements
(
    achievement_id bigint not null
        constraint fkqxi71alapdncp806nakeioemx
            references ivavprp.achievement,
    skill_id bigint not null
        constraint fk3bhc9vrvwpnylu29ivrdb9psd
            references ivavprp.skill
);
​
alter table ivavprp.skills_achievements owner to postgres;
​
-- auto-generated definition
create table ivavprp.vacancy
(
    id bigint generated by default as identity
        constraint vacancy_pkey
            primary key,
    employment_type varchar(255),
    max integer,
    min integer,
    name varchar(255),
    text varchar(255),
    time timestamp,
    work_schedule varchar(255)
);
​
alter table ivavprp.vacancy owner to postgres;
​
​
create unique index vacancy_id_uindex
    on ivavprp.vacancy (id);
​
​
-- auto-generated definition
create table ivavprp.skills_vacancies
(
    vacancy_id bigint not null
        constraint fkfmyc24s5nbfhjv3dlp50qxutw
            references ivavprp.vacancy,
    skill_id bigint not null
        constraint fk8trggkx78qpvhorwss4je82bh
            references ivavprp.skill
);
​
alter table ivavprp.skills_vacancies owner to postgres;
​
create table ivavprp.resume
(
    id bigserial not null
        constraint resume_pk
            primary key,
    name varchar(255) not null,
    text text not null,
    employment_type varchar(20) not null,
    work_schedule varchar(20) not null
);
​
alter table ivavprp.resume owner to postgres;
​
create unique index resume_id_uindex
    on ivavprp.resume (id);
​
create table ivavprp.skills_resumes
(
    skill_id bigint,
    resume_id bigint
);
​
alter table ivavprp.skills_resumes owner to postgres;

create table ivavprp.users
(
    id bigint not null
        constraint users_pkey
            primary key,
    email varchar(255),
    is_active boolean,
    password varchar(255)
);
alter table ivavprp.users owner to postgres;
create table ivavprp.user_role
(
    user_id bigint not null
        constraint fkj345gk1bovqvfame88rcx7yyx
            references ivavprp.users,
    roles varchar(255)
);
alter table ivavprp.user_role owner to postgres;
create table ivavprp.company
(
    about varchar(255),
    name varchar(255),
    photo varchar(255),
    id bigint not null
        constraint company_pkey
            primary key
        constraint fkfydf11ujy2p70ywt0goq9klow
            references ivavprp.users
);
alter table ivavprp.company owner to postgres;
create table ivavprp.student
(
    course integer,
    first_name varchar(255),
    last_name varchar(255),
    photo varchar(255),
    rating integer,
    id bigint not null
        constraint student_pkey
            primary key
        constraint fk3w7xmt19i6a0cr7kp8c80ek40
            references ivavprp.users
);
alter table ivavprp.student owner to postgres;
create table ivavprp.teacher
(
    first_name varchar(255),
    last_name varchar(255),
    photo varchar(255),
    id bigint not null
        constraint teacher_pkey
            primary key
        constraint fkspqy2s83gvl6g8nt5aubls90k
            references ivavprp.users
);
alter table ivavprp.teacher owner to postgres;